### ISSUE TITLE
TODO `letloop root`

### ISSUE THREAD

**Issue by amirouche** [letloop/letloop#3]
Add a `root` subcommand to help with chroot, container, and vm testing, respectively built on top of chroot, maybe proot, `systemd-nspawn`, and `qemu`.

```bash
letloop root available
letloop root init --without-dev --without-kernel DISTRIBUTION VERSION [DIRECTORY]
letloop root exec DIRECTORY [TARGET-DIRECTORY] [KEY=VALUE ...] -- COMMAND ARGS ...
letloop root spawn DIRECTORY
letloop root emulate DIRECTORY
```

- [x] Initial implementation, see `(letloop root)`
- [x] Use bubblewrap https://github.com/containers/bubblewrap, cf. https://github.com/containers/bubblewrap/issues/668
- [x] Add the subcommand to the CLI
- [ ] Add documentation
- [x] Rename command-parse into `cli-read`, and move it to `(letloop cli)`
- [ ] #28
- [x] Add `root-chroot-exec` that use `chroot`
- [ ] #29
- [ ] ...

**Comment by amirouche** [comment]
I did not want to close the issue 😬

**Comment by amirouche** [comment]
Documentation will be done in a dedicated ticket. In the meantime closing it as done.
